/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.tuke.kpi.ssce.gui;

/**
 * Trieda predstavuje GUI panel zobrazujuci hlasku "No View Available".
 * @author Matej Nosal
 */
//SsceIntent:Komponent grafickeho rozhrania;
public class NoViewAvailablePanel extends javax.swing.JPanel {

    /**
     * Creates new form NoViewAvailablePanel
     */
    //SsceIntent:Komponent grafickeho rozhrania;
    public NoViewAvailablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelText = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        setLayout(new java.awt.GridBagLayout());

        jLabelText.setForeground(javax.swing.UIManager.getDefaults().getColor("Label.disabledForeground"));
        jLabelText.setText(org.openide.util.NbBundle.getMessage(NoViewAvailablePanel.class, "NoViewAvailablePanel.jLabelText.text")); // NOI18N
        add(jLabelText, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelText;
    // End of variables declaration//GEN-END:variables
}
